// This testing module was generated by Claude 3.7 Sonnet on 3/8/25.
use std::time::{Duration, Instant};
use std::collections::HashMap as StdHashMap;
use std::hash::Hash;
use rand::{Rng, SeedableRng};
use rand::rngs::StdRng;


// Import your custom HashMap
use crate::hash_map::HashMap as CustomHashMap;
use crate::hash::JacobHash;

fn run_insert_benchmark<K, V, F>(name: &str, iterations: usize, key_fn: F)
where
K: JacobHash + Clone + PartialEq + std::fmt::Debug + std::fmt::Display + Eq + Hash,
V: Clone + PartialEq + std::fmt::Debug + std::fmt::Display,
F: Fn(i32) -> K
{
    println!("===== {} Insert Benchmark =====", name);

    // Setup random number generator with fixed seed for reproducibility
    let mut rng = StdRng::seed_from_u64(42);

    // Benchmark custom HashMap
    let start = Instant::now();
    let mut custom_map = CustomHashMap::new();
    for i in 0..iterations {
        let key = key_fn(rng.random_range(0..100000));
        let value = i as i32;
        custom_map.insert(key, value);
    }
    let custom_duration = start.elapsed();

    // Benchmark standard HashMap
    let start = Instant::now();
    let mut std_map = StdHashMap::new();
    // Reset RNG to get the same sequence
    let mut rng = StdRng::seed_from_u64(42);
    for i in 0..iterations {
        let key = key_fn(rng.random_range(0..100000));
        let value = i as i32;
        std_map.insert(key, value);
    }
    let std_duration = start.elapsed();

    print_results("Insert", iterations, custom_duration, std_duration);
}

fn run_get_benchmark<K, V, F>(name: &str, iterations: usize, hit_ratio: f64, key_fn: F)
where
K: JacobHash + Clone + PartialEq + std::fmt::Debug + std::fmt::Display + Eq,
V: Clone + PartialEq + std::fmt::Debug + std::fmt::Display,
F: Fn(i32) -> K, K: Hash
{
    println!("===== {} Get Benchmark ({}% hits) =====", name, hit_ratio * 100.0);

    // Setup maps with initial data
    let mut rng = StdRng::seed_from_u64(42);
    let mut custom_map = CustomHashMap::new();
    let mut std_map = StdHashMap::new();
    let data_size = iterations / 2;

    // Fill maps with initial data
    for i in 0..data_size {
        let key = key_fn(i as i32);
        let value = i as i32;
        custom_map.insert(key.clone(), value);
        std_map.insert(key, value);
    }

    // Prepare keys to look up (some existing, some not)
    let mut keys = Vec::with_capacity(iterations);
    for _ in 0..iterations {
        if rng.random_bool(hit_ratio) {
            // Use an existing key
            keys.push(key_fn(rng.random_range(0..data_size) as i32));
        } else {
            // Use a non-existing key
            keys.push(key_fn(rng.random_range(data_size as i32..100000)));
        }
    }

    // Benchmark custom HashMap lookups
    let start = Instant::now();
    let mut hits = 0;
    for key in &keys {
        if custom_map.get(key).is_some() {
            hits += 1;
        }
    }
    let custom_duration = start.elapsed();

    // Benchmark standard HashMap lookups
    let start = Instant::now();
    let mut std_hits = 0;
    for key in &keys {
        if std_map.get(key).is_some() {
            std_hits += 1;
        }
    }
    let std_duration = start.elapsed();

    assert_eq!(hits, std_hits, "Hit counts should match between implementations");
    print_results("Get", iterations, custom_duration, std_duration);
}

fn run_remove_benchmark<K, V, F>(name: &str, iterations: usize, key_fn: F)
where
K: JacobHash + Clone + PartialEq + std::fmt::Debug + std::fmt::Display + Eq + std::hash::Hash,
V: Clone + PartialEq + std::fmt::Debug + std::fmt::Display,
F: Fn(i32) -> K
{
    println!("===== {} Remove Benchmark =====", name);

    // Setup maps with initial data
    let data_size = iterations;
    let mut custom_map = CustomHashMap::new();
    let mut std_map = StdHashMap::new();

    // Fill maps with initial data
    for i in 0..data_size {
        let key = key_fn(i as i32);
        let value = i as i32;
        custom_map.insert(key.clone(), value);
        std_map.insert(key, value);
    }

    // Prepare keys to remove in random order
    let mut rng = StdRng::seed_from_u64(42);
    let mut keys: Vec<i32> = (0..data_size as i32).collect();
    keys.shuffle(&mut rng);

    // Benchmark custom HashMap removals
    let start = Instant::now();
    for i in 0..iterations {
        if i < keys.len() {
            let key = key_fn(keys[i]);
            custom_map.remove(&key);
        }
    }
    let custom_duration = start.elapsed();

    // Reset maps
    let mut custom_map = CustomHashMap::new();
    let mut std_map = StdHashMap::new();
    for i in 0..data_size {
        let key = key_fn(i as i32);
        let value = i as i32;
        custom_map.insert(key.clone(), value);
        std_map.insert(key, value);
    }

    // Benchmark standard HashMap removals
    let start = Instant::now();
    for i in 0..iterations {
        if i < keys.len() {
            let key = key_fn(keys[i]);
            std_map.remove(&key);
        }
    }
    let std_duration = start.elapsed();

    print_results("Remove", iterations, custom_duration, std_duration);
}

fn run_iterator_benchmark<K, V, F>(name: &str, iterations: usize, key_fn: F)
where
K: JacobHash + Clone + PartialEq + std::fmt::Debug + std::fmt::Display + Eq + std::hash::Hash,
V: Clone + PartialEq + std::fmt::Debug + std::fmt::Display,
F: Fn(i32) -> K
{
    println!("===== {} Iterator Benchmark =====", name);

    // Setup maps with initial data
    let data_size = iterations;
    let mut custom_map = CustomHashMap::new();
    let mut std_map = StdHashMap::new();

    // Fill maps with initial data
    for i in 0..data_size {
        let key = key_fn(i as i32);
        let value = i as i32;
        custom_map.insert(key.clone(), value);
        std_map.insert(key, value);
    }

    // Benchmark custom HashMap iteration
    let start = Instant::now();
    let mut sum: i64 = 0;
    for pair in custom_map.iter() {
        // Convert value to i64 
        if let Ok(n) = pair.value.to_string().parse::<i32>() {
            sum += n as i64;
        }
    }
    let custom_duration = start.elapsed();

    // Benchmark standard HashMap iteration
    let start = Instant::now();
    let mut std_sum: i64 = 0;
    for (_, value) in &std_map {
        if let Ok(n) = value.to_string().parse::<i32>() {
            std_sum += n as i64;
        }
    }
    let std_duration = start.elapsed();

    assert_eq!(sum, std_sum as i64, "Sums should match between implementations");
    print_results("Iterate", iterations, custom_duration, std_duration);
}

fn print_results(operation: &str, iterations: usize, custom_duration: Duration, std_duration: Duration) {
    println!("{} x{}: Custom: {:?}, Std: {:?}", operation, iterations, custom_duration, std_duration);
    println!("Ratio (Custom/Std): {:.2}x", custom_duration.as_nanos() as f64 / std_duration.as_nanos() as f64);
    println!();
}

pub(crate) fn run_all_tests() {
    // Run benchmarks with different sizes
    let sizes = [1_000, 10_000, 100_000];

    for &size in &sizes {
        println!("\n==================================================");
        println!("Running benchmarks with {size} operations");
        println!("==================================================");

        // Modify these functions to use types that your JacobHash trait supports
        // Integer benchmark
        run_insert_benchmark::<i32, i32, _>("Integer Keys", size, |x| x);
        run_get_benchmark::<i32, i32, _>("Integer Keys", size, 0.8, |x| x);
        run_remove_benchmark::<i32, i32, _>("Integer Keys", size, |x| x);
        run_iterator_benchmark::<i32, i32, _>("Integer Keys", size, |x| x);

        // String benchmark (optional - use only if your JacobHash supports String)
        if size <= 10_000 {
            println!("\n----- String Key Benchmarks -----\n");
            run_insert_benchmark::<String, i32, _>("String Keys", size, |x| format!("key-{}", x));
            run_get_benchmark::<String, i32, _>("String Keys", size, 0.8, |x| format!("key-{}", x));
            run_remove_benchmark::<String, i32, _>("String Keys", size, |x| format!("key-{}", x));
            run_iterator_benchmark::<String, i32, _>("String Keys", size, |x| format!("key-{}", x));
        }
    }
}

// Shuffle trait implementation to support vec shuffling
trait VecExtension<T> {
    fn shuffle(&mut self, rng: &mut StdRng);
}

impl<T> VecExtension<T> for Vec<T> {
    fn shuffle(&mut self, rng: &mut StdRng) {
        for i in (1..self.len()).rev() {
            let j = rng.random_range(0..=i);
            self.swap(i, j);
        }
    }
}